### ISSUE TITLE
Provide documentation

### ISSUE THREAD

**Issue by nikitap492** [palyuga/BitbucketHelper4Idea#11]
Provide documentation or wiki of the project

**Comment by palyuga** [comment]
Could you specify what kind of documentation should we start with?
Is it some documentation for users to setup the plugin or about using it, or it will be for developers?

**Comment by nikitap492** [comment]
Yes, sure.
In my opinion, the most important parts are
1) Add more detail of the plugin 
2) Describe the features of the plugin
3) How to pages (how to use the plugin, how to setup plugin etc.)
It's more an user orientated

I created the issue just in case not to forget and not to put it off with
The issue has a low priority

**Comment by palyuga** [comment]
Reloved by #40
