### ISSUE TITLE
Checkout works incorrectly

### ISSUE THREAD

**Issue by nikitap492** [palyuga/BitbucketHelper4Idea#20]
I try to checkout my PR request and when checnkout is done, I cannot see my changes under the PR.

**Comment by palyuga** [comment]
Does it happen with any of your PRs, which revision is checked out in this case?
What about PRs that are not yours, is there the same issue?

**Comment by palyuga** [comment]
I am able to reproduce this with any branch that does not exist in my local repo. 
Looking at the suspicios speed of checking out I am assuming that git does something like `git checkout -b <branch_name>` now instead of a real checkout
