### ISSUE TITLE
Redesign reviewers' images panel

### ISSUE THREAD

**Issue by palyuga** [palyuga/BitbucketHelper4Idea#30]
<img width="518" alt="rev" src="https://user-images.githubusercontent.com/927387/50059361-f2b23c00-0196-11e9-8c99-563b8fd098a0.png">
Now reviewers are displayed in two sections: "Approved:" and "Others:".
Those who clicked "Needs work" are among "Others:" in random order. 
1. We need to display reviewers in order: approved, needs work, others.
2. Do not need to mark each group with words (will have too many words)
3. If we have more than 5 reviewers in total, let's display `+N` label, where N is a number of other reviewers.
(we still need to display all the "Approvers" and "Needs work guys" without shrinking)

**Comment by a-krasilnikov** [comment]
fixed in #49
