### ISSUE TITLE
Use links to pull requests from Bitbucket JSON response

### ISSUE THREAD

**Issue by palyuga** [palyuga/BitbucketHelper4Idea#6]
Now pull-request link is hardcoded inside PRComponent's constructor.
We need to add Link field to the PR object to receive the link from bitbucket and use it inside PRComponent.

**Comment by nikitap492** [comment]
@palyuga Could you please close the issue. The PR is merged

**Comment by palyuga** [comment]
@nikitap492, sure, thanks!
