### ISSUE TITLE
Error while getting pull requests

### ISSUE THREAD

**Issue by pysabwork** [palyuga/BitbucketHelper4Idea#72]
Hello,

I'm trying to use the plugin but at the moment without success. Let me give you the context:
PyCharm Version 2019.3
Bitbucket Server v5.16.0
I try to connect with a personal token. 

I get this error in PyCharm console:
Request to BitBucket failed, it may be unreachable or the settings are incorrect. Details: Instantiation of [simple type, class bitbucket.data.User] value failed: Parameter specified as non-null is null: method bitbucket.data.User.<init>, parameter emailAddress (through reference chain: bitbucket.data.PagedResponse["values"]->java.util.ArrayList[1]->bitbucket.data.PR["author"]->bitbucket.data.PRParticipant["user"])

I've checked on Bitbucket log, I can see my requests with status code 200:
GET /rest/api/1.0/inbox/pull-requests HTTP/1.1" | "" "Apache-HttpClient/4.5.10 (Java/11.0.6)" | 200

Do you have an idea what could be wrong in my case?
I can send you the full traceback of the error in Pycharm if you need it. But here is an extract:

 #UpdateTaskHolder - Request failed 
com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class bitbucket.data.User] value failed: Parameter specified as non-null is null: method bitbucket.data.User.<init>, parameter emailAddress (through reference chain: bitbucket.data.PagedResponse["values"]->java.util.ArrayList[1]->bitbucket.data.PR["author"]->bitbucket.data.PRParticipant["user"])

Thanks in advance for any help you could give. 
I'm looking forward to using the plugin!
Best Regards,
Sabrina

**Comment by svlukas** [comment]
Hi Sabrina.
Thanks for you feedback. What can I see from the error is that the user doesn't have an email specified in bitbucket account. Can you check that? 
We didn't expect this in our code (and looks like this is something we should fix). I will take a look.

**Comment by pysabwork** [comment]
Hi,

Thanks for your reply. 

The user has an email for what I see. Our users are not local users of bitbucket (from the internal directory) but users from an external Active Directory. Maybe it can explain that the email is not found? 

Tomorrow, I can make a try with a local user (I have only one and it's the admin user so it won't be a permanent solution for me but at least to see if the issue comes from this or not).

Regards,
Sabrina

**Comment by pysabwork** [comment]
Hi again,

I have just tested with my local admin user and the result is the same. Same error. 

Sabrina

**Comment by pysabwork** [comment]
Hi there,

I saw that you merge a fix for this issue. Well done! Do you know when you are going to release version 0.4? Is there an other way to test the plugin with the current master branch?

Best regards,
Sabrina

**Comment by svlukas** [comment]
Hi.
We created 0.4 today and pushed to Jetbrains. It should be available in a two days from now.

**Comment by svlukas** [comment]
Version 0.4 is now available.

**Comment by pysabwork** [comment]
Hi!
I've just updated it and it has solved my issue, I can now see the pull requests. 
Thanks! You'd been very efficient :)

Best regards,
Sabrina
